### ISSUE TITLE
todo list for upcoming release

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#192]
These items are related to the VERDI release packages
- [ ] update PDF under ./plugins/bootstrap/help within VERDI distribution prior to final build so new version of User Manual is available VERDI (Liz)
- [x] rename VERDI_1.6.0_alpha (home directory) to VERDI_2.0_beta (Liz or Tony)
- [ ] update INSTALL.mac.txt  (also windows and linux versions)
- [ ] update RELEASE-NOTES.txt

These items are related to the CMAS website
- [ ] add the documentation (RELEASE-NOTES.txt, PDF version of User Manual)

These items are related to the github site
- [x] create a github release - Tony did this

Additional testing
- [x] Test areal interpolation plot export of shapefile

Note: we now have duplicate copies of the map_world file.  I had created a subdirectory, called map_world and placed the files there, and pointed to them in the code.  Did this not work?

(py36) Elizabeths-MacBook-Pro:data lizadams$ cd map_world
(py36) Elizabeths-MacBook-Pro:map_world lizadams$ ls
Department_of_State_Valid_QGIS.cpg	Department_of_State_Valid_QGIS.qpj
Department_of_State_Valid_QGIS.dbf	Department_of_State_Valid_QGIS.shp
Department_of_State_Valid_QGIS.prj	Department_of_State_Valid_QGIS.shx

**Comment by lizadams** [comment]
Additional tests needed for shapefile export
- [ ] mpas all uses same projections
- [ ] test export of shapefile for different projections, lambert, polar stereographic, mercator, lat/lon

**Comment by lizadams** [comment]
closing -
